### ISSUE TITLE
Problem with Home Assistant 2024.3

### ISSUE THREAD

**Issue by Hoarerport** [briis/weatherbit#96]
Hi,
this Problem is found after Installing weatherbit on Home Assistant 2024.3
"Logger: homeassistant.components.weather
Source: components/weather/__init__.py:387
Integration: Wetter (documentation, issues)

weatherbit::WeatherbitWeatherEntity implements the `forecast` property or sets `self._attr_forecast` in a subclass of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. "

Please update the Entitiy. Thanks
Pauker

**Comment by briis** [comment]
Please ser the README om the front page. Unless someone else wants to continue this integration it will close down in march.

**Comment by Hoarerport** [comment]
Ok, sorry unfortunately I missed your information. Thanks for your answer and your work. It's a shame that it doesn't continue. The solar radiation values in particular would have been interesting : translation with google ;-)
greetings Pauker

**Comment by greg520820** [comment]
You can still pull weatherbit values by using a rest command. Example code below was added to configuration.yaml.  You can set your desired scan interval in the rest command or set it very high, like the example, and use an automation to update the sensors .  I'm updating every 30 minutes, but only between sunrise and dusk.  

```
rest:
  - scan_interval: 86400
    resource: "https://api.weatherbit.io/v2.0/current?lat=xx.1127&lon=-xx.3911&key=xxxxxxxxxxxxx"
    sensor:
      - name: "AQI"
        value_template: "{{ value_json['data'][0]['aqi'] }}"

      - name: "Solar"
        value_template: "{{ value_json['data'][0]['solar_rad'] | round(0) }}"
        unit_of_measurement: "W/M2"
```
